name: Flutter Firebase Distribution

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create .env
        run: |
          echo "API_BASE_URL=${{ vars.API_BASE_URL }}" >> .env
          echo "APP_ENV=${{ vars.APP_ENV }}" >> .env
          echo "SUPABASE_URL=${{ vars.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "PROFILE_PHOTO_BUCKET=${{ vars.PROFILE_PHOTO_BUCKET }}" >> .env

      - name: Build APK
        run: flutter build apk --release --dart-define-from-file=.env

      - name: Upload APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testeurs-dev
          file: build/app/outputs/flutter-apk/app-release.apk